#[macro_use]
extern crate error_chain;

/// This crate's error-related code, generated by `error-chain`.
mod errors {
    // Create the Error, ErrorKind, ResultExt, and Result types
    error_chain! {}
}

pub use errors::*;

extern crate clap;

#[macro_use]
extern crate slog;
use slog::Logger;

mod options;
pub use options::*;

pub fn run(logger: Logger, options: ScanOptions) -> Result<()> {
    debug!(logger, "Running tell-tool scan, options = {:?}", &options);
    Ok(())
}
